sudo: false

language: go

matrix:
  include:
    - go: 1.4

install:
  - go get github.com/tools/godep
  - go get golang.org/x/tools/cmd/goimports
  - ./hack/travis/install-etcd.sh
  - ./hack/build-go.sh
  - export PATH=$GOPATH/bin:./third_party/etcd:$PATH

script:
  - ./hack/verify-gofmt.sh
  - ./hack/verify-boilerplate.sh
  - ./hack/verify-description.sh
  - ./hack/verify-generated-conversions.sh
  - ./hack/verify-generated-deep-copies.sh
  - ./hack/verify-generated-docs.sh
  - ./hack/verify-swagger-spec.sh
  - ./hack/verify-linkcheck.sh

notifications:
  irc: "chat.freenode.net#kubernetes-dev"
